// Standards-based study plans for O'Connor courses that have no public district curriculum.
// Goals come from published standards: Arizona (via azstandards.js, cited by code) or, for AP and
// national programs, Orbit's own paraphrase of the framework named in `sources`. Key terms are
// Orbit's own. See dvcurriculum.js for how these are used.
import { std, unit, plan, ext, cteUnits, arts } from './stdkit.js';
import { CTE_TERMS } from './terms-cte.js';

const CB = (slug, name) => ext(`College Board — ${name} course overview`, `https://apcentral.collegeboard.org/courses/${slug}`);
const ASCA = ext('ASCA Student Standards: Mindsets & Behaviors for Student Success', 'https://www.schoolcounselor.org/About-School-Counseling/ASCA-Mindsets-Behaviors-for-Student-Success');
const CASEL = ext('CASEL framework for social and emotional learning', 'https://casel.org/fundamentals-of-sel/what-is-the-casel-framework/');
const LSCI = ext('The Learning Scientists — six strategies for effective learning', 'https://www.learningscientists.org/downloadable-materials');
const USAD = ext('United States Academic Decathlon — 2026–27 curriculum', 'https://usad.org/curriculum');
const AFJROTC = ext('Air Force JROTC fact sheet (curriculum overview)', 'https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104476/air-force-junior-reserve-officer-training-corps/');
const NASM = ext('NASM Certified Personal Trainer', 'https://www.nasm.org/certified-personal-trainer');

// ------------------------------------------------------------------ CTE programs (AZ CTE standards)
const PRO = unit('Professional skills (all CTE programs)', [std('proskills', /^(1\.A|2\.A|3\.C|4\.A|4\.B|5\.A|8\.C|8\.H)$/)], [
  'Professionalism|Behaving in a way that meets an employer’s expectations: reliable, respectful, prepared.', 'Soft skills|Interpersonal skills such as communication, teamwork and adaptability.', 'Work ethic|A commitment to doing quality work on time.', 'Workplace safety|Following procedures that prevent injuries.', 'CTSO|Career and technical student organization (e.g. DECA, FBLA, HOSA, SkillsUSA, FCCLA).', 'Industry credential|A certification showing job-ready skills.',
]);
const cte = (set, label, extra = []) => plan(label, [set, 'proskills'], [...cteUnits(set, CTE_TERMS[set]), ...extra, PRO]);

export const DEEP_CTE = {
  accounting: cte('accounting', 'Accounting'),
  construction: plan('Construction Technologies', ['construction', 'proskills', ext('NCCER Core Curriculum', 'https://www.nccer.org/craft-catalog/core/')], [...cteUnits('construction', CTE_TERMS.construction), PRO]),
  sportsmed: cte('sportsmed', 'Sports Medicine'),
  pt: cte('pt', 'Physical Therapy Tech'),
  digitalcomm: cte('digitalcomm', 'Digital Communications'),
  earlychild: cte('earlychild', 'Early Childhood Education'),
  eduprof: cte('eduprof', 'Education Professions'),
  film: cte('film', 'Film & TV Production'),
  graphic: cte('graphic', 'Graphic Design'),
  marketing: cte('marketing', 'Marketing'),
  software: cte('software', 'Software and App Design'),
  nasm: plan('NASM Certified Personal Trainer', ['sportsmed', NASM], [
    unit('Human movement science', [std('sportsmed', /^2\./, 4), 'Describe the kinetic chain and how muscles work together as agonists, antagonists, synergists and stabilizers'], ['Kinetic chain|The nervous, muscular and skeletal systems working together to produce movement.', 'Agonist|The prime mover muscle for a movement.', 'Antagonist|The muscle that opposes the agonist.', 'Synergist|A muscle that assists the prime mover.', 'Planes of motion|Sagittal (forward/back), frontal (side to side), transverse (rotation).', 'Length-tension relationship|A muscle produces the most force at its resting length.']),
    unit('Assessment', ['Assess posture and identify muscle imbalances', 'Conduct a health history (PAR-Q+) and basic fitness assessments', 'Identify common movement compensations in an overhead squat assessment'], ['PAR-Q+|Physical Activity Readiness Questionnaire used to screen clients.', 'Overhead squat assessment|A movement screen that reveals muscle imbalances.', 'Resting heart rate|Heart beats per minute at rest.', 'Body composition|Proportions of fat and lean mass.', 'Muscle imbalance|Altered length or strength between muscles around a joint.']),
    unit('The OPT model & program design', ['Choose exercises and progressions for clients with different goals', 'Explain the phases of a periodized training model', 'Write a safe training program with sets, reps, tempo and rest'], ['Periodization|Planned variation of training over time.', 'Stabilization endurance|Training phase building balance, core stability and endurance.', 'Strength phase|Training phase building muscular strength and hypertrophy.', 'Power phase|Training phase combining strength and speed.', 'Acute variables|Sets, reps, intensity, tempo and rest that define a workout.', 'Progressive overload|Gradually increasing training demands.']),
    unit('Flexibility, cardio & core', [std('sportsmed', /^3\.[1-4]$/, 3), 'Choose appropriate flexibility techniques for each training phase'], ['Self-myofascial release|Foam rolling to reduce tissue tension.', 'Static stretching|Holding a stretch for about 30 seconds.', 'Dynamic stretching|Moving a joint through its range at controlled speed.', 'Heart rate zones|Training intensity ranges based on maximum heart rate.', 'Core|Muscles of the lumbo-pelvic-hip complex and trunk that stabilize the spine.']),
    unit('Nutrition, behavior change & the business of training', [std('sportsmed', /^3\.[5-7]$/, 3), 'Use goal setting and motivational strategies to support client change', 'Explain a trainer’s scope of practice'], ['Macronutrients|Protein, carbohydrate and fat.', 'Calorie balance|Energy intake vs. energy expenditure.', 'SMART goal|Specific, Measurable, Attainable, Realistic, Timely goal.', 'Scope of practice|Trainers do not diagnose or prescribe diets.', 'CPR/AED certification|Required for trainer certification.']),
  ]),
  jrotc: plan('Air Force JROTC (Aerospace Science & Leadership Education)', ['jrotc', AFJROTC], [
    ...cteUnits('jrotc', CTE_TERMS.jrotc),
    unit('History of flight', ['Explain how aviation technology changed travel, commerce and warfare', 'Trace milestones in aviation from early balloons to the jet age', 'Explain the role of air power in modern conflicts'], ['Wright brothers|First sustained, controlled, powered flight in 1903 at Kitty Hawk.', 'Montgolfier brothers|Launched the first manned hot-air balloon flight (1783).', 'Tuskegee Airmen|First African American military aviators in the U.S. armed forces (WWII).', 'Chuck Yeager|First pilot to break the sound barrier (1947).', 'U.S. Air Force|Became a separate military branch in 1947.']),
    unit('Principles of flight & navigation', ['Describe how weather (wind, density, storms) affects flight', 'Explain how the four forces of flight act on an aircraft', 'Use basic navigation concepts and weather knowledge for flight planning'], ['Four forces of flight|Lift, weight, thrust and drag.', 'Bernoulli’s principle|Faster-moving air has lower pressure, helping wings generate lift.', 'Angle of attack|Angle between the wing and the oncoming air.', 'Pitch, roll, yaw|Rotation around the lateral, longitudinal and vertical axes.', 'Latitude and longitude|Coordinates used to locate points on Earth.', 'Airfoil|The curved shape of a wing that produces lift.']),
    unit('Space exploration', ['Explain the U.S. space program’s milestones from Mercury to Artemis', 'Describe major space programs and how spacecraft reach orbit', 'Explain the challenges of human spaceflight'], ['Artemis program|NASA program to return humans to the Moon.', 'Orbit|The curved path of an object around a planet or star.', 'Escape velocity|The speed needed to break free of a body’s gravity.', 'Apollo 11|1969 mission that landed the first humans on the Moon.', 'International Space Station|A crewed orbiting laboratory operated by several nations.', 'U.S. Space Force|Military branch established in 2019 to organize space forces.']),
  ]),
};

// The accounting-technology standard has only two measures; add a hands-on goal.
DEEP_CTE.accounting.units[7].topics.push('Record transactions, reconcile accounts and run financial reports in accounting software');

// ------------------------------------------------------------------ AP Capstone (College Board)
const QUEST = [
  'Question & explore|The first step of inquiry: identify a problem, issue or topic and ask questions about it.',
  'Lens|A perspective used to examine an issue: cultural & social, artistic & philosophical, economic, environmental, ethical, futuristic, historical, political or scientific.',
  'Stakeholder|A person or group affected by an issue or by a proposed solution.',
];
export const DEEP_CAP = {
  apsem: plan('AP Seminar', [CB('ap-seminar', 'AP Seminar'), 'ela1112'], [
    unit('Big Idea 1: Question and Explore', ['Identify a problem or issue and turn it into a focused inquiry question', 'Locate, filter and select sources for credibility and relevance', 'Consider the context and scope of the issue', std('ela1112', /^11-12\.W\.7$/)], [...QUEST, 'Inquiry question|An open, researchable question that guides investigation.', 'Credibility|How trustworthy a source is (author expertise, publisher, evidence, bias).', 'Relevance|How directly a source relates to the research question.', 'Peer-reviewed|Checked by other experts before publication.', 'Scholarly vs popular source|Written by experts for experts (journals) vs. for a general audience.']),
    unit('Big Idea 2: Understand and Analyze', ['Explain an author’s argument, main idea and line of reasoning', 'Evaluate the quality of evidence and the strength of reasoning', 'Explain the implications and consequences of an argument', std('ela1112', /^11-12\.RI\.[68]$/)], ['Argument|A claim supported by reasoning and evidence.', 'Claim|A statement the author wants the audience to accept.', 'Line of reasoning|The logical sequence of claims connecting evidence to a conclusion.', 'Evidence types|Quantitative data, qualitative data, expert testimony, anecdotes, examples.', 'Validity|Whether reasoning is logical and conclusions follow from evidence.', 'Reliability|Whether evidence and sources are consistent and dependable.', 'Bias|A slant that can distort how evidence is chosen or presented.', 'Implication|A likely consequence that follows from an argument.']),
    unit('Big Idea 3: Evaluate Multiple Perspectives', ['Identify and compare different perspectives on an issue', 'Evaluate objections, implications and limitations of each perspective', std('hss', /^HS\.SP2\.[12]$/)], ['Perspective|A point of view on an issue shaped by background, values and lens.', 'Counterargument|An opposing view a writer must address.', 'Concession|Acknowledging a valid point in an opposing view.', 'Rebuttal|A response showing weaknesses in an opposing view.', 'Worldview|A set of beliefs and assumptions through which someone sees the world.']),
    unit('Big Idea 4: Synthesize Ideas', ['Combine information from several sources to form your own argument', 'Offer a resolution, conclusion or solution and explain its limitations', 'Attribute and cite all sources ethically', std('ela1112', /^11-12\.W\.[18]$/)], ['Synthesis|Combining ideas from several sources into a new understanding.', 'Thesis|The central claim of an argument.', 'Paraphrase|Restating an idea in your own words (still cited).', 'Attribution|Crediting the source of an idea or quotation.', 'Plagiarism|Presenting others’ work or ideas as your own.', 'Limitation|A weakness or boundary of an argument or solution.']),
    unit('Big Idea 5: Team, Transform, and Transmit', ['Collaborate on a team project, contributing to shared goals', 'Adapt an argument for an audience in a multimedia presentation', 'Answer oral defense questions and reflect on your process', std('ela1112', /^11-12\.SL\.[145]$/)], ['Collaboration|Working with others toward a shared goal.', 'Audience|The people a presentation is designed for.', 'Oral defense|Answering questions about your research and choices.', 'Reflection|Thinking about what worked, what didn’t and why.', 'Visual design|Using images, layout and text to support a spoken argument.']),
    unit('Performance tasks & end-of-course exam', ['Use the scoring rubrics to self-assess drafts before submission', 'Know the structure and weighting of AP Seminar assessments', 'Plan research and writing time for each performance task'], ['Team Project and Presentation|Performance task 1: individual research report plus team multimedia presentation and oral defense (20% of the AP score).', 'Individual Research-Based Essay and Presentation|Performance task 2: written argument and presentation with oral defense, using provided stimulus texts (35%).', 'End-of-course exam|Timed exam with short-answer questions on a source and an argument essay synthesizing sources (45%).', 'Stimulus materials|Texts released by the College Board that students use to find a research topic.', 'Academic integrity|Doing your own work and acknowledging others’ ideas; required on all tasks.']),
  ]),
  apres: plan('AP Research', [CB('ap-research', 'AP Research'), 'ela1112'], [
    unit('Choosing a topic & research question', ['Find a gap in existing research and write a focused research question', 'Explain why the question matters and to whom', std('ela1112', /^11-12\.W\.7$/)], [...QUEST, 'Gap in the research|An unanswered question or understudied area found through the literature.', 'Research question|A focused, answerable question that the study addresses.', 'Scope|The boundaries of what a study will and will not cover.', 'Hypothesis|A testable prediction (used in some methods).']),
    unit('Literature review', ['Read, summarize and evaluate scholarly sources', 'Organize sources by theme to show the current conversation on a topic', std('ela1112', /^11-12\.W\.8$/)], ['Literature review|Synthesis of existing scholarship on a topic.', 'Scholarly conversation|The ongoing exchange of ideas among researchers.', 'Peer review|Evaluation of research by experts before publication.', 'Database|Searchable collection of articles (e.g. JSTOR, Google Scholar).', 'Annotated bibliography|A list of sources with summaries and evaluations.', 'Citation style (APA)|Author-date style used in many research fields.']),
    unit('Research methods & ethics', ['Choose a method that fits the research question', 'Follow ethical standards for research with human participants', 'Plan data collection that is valid and reliable'], ['Qualitative method|Research using non-numerical data such as interviews or texts.', 'Quantitative method|Research using numerical data and statistics.', 'Mixed methods|Combining qualitative and quantitative approaches.', 'Survey|Questions asked of a sample to gather data.', 'Experiment|Manipulating a variable to measure its effect.', 'Content analysis|Systematic coding of texts or media.', 'IRB|Institutional review board that approves research with human subjects.', 'Informed consent|Participants agree after understanding the study and its risks.', 'Sampling bias|When a sample does not represent the population.']),
    unit('Analyzing data & drawing conclusions', ['Analyze data accurately and explain what it shows', 'Connect findings to the research question and the literature', 'Acknowledge limitations and suggest future research'], ['Operationalize|Define a concept so it can be measured.', 'Validity|Whether a study measures what it claims to.', 'Reliability|Whether a study would give the same results if repeated.', 'Triangulation|Using several data sources or methods to confirm findings.', 'Correlation vs causation|A relationship between variables does not prove one causes the other.', 'Coding|Labeling qualitative data to find patterns.', 'New understanding|The contribution a study adds to the field.']),
    unit('Academic paper', ['Write a 4,000–5,000 word paper with the standard research sections', 'Revise for clarity, organization and accurate citation', std('ela1112', /^11-12\.W\.[245]$/)], ['Abstract|A short summary of a study’s question, method, findings and significance.', 'Introduction|Section presenting the topic, gap and research question.', 'Method section|Explains how the study was done so it can be replicated.', 'Results|Section reporting what the data showed.', 'Discussion|Section interpreting results, limitations and implications.', 'Academic paper (AP Research)|Worth 75% of the AP Research score.']),
    unit('Presentation & oral defense', ['Present research clearly to a panel in 15–20 minutes', 'Answer oral defense questions about choices and process', std('ela1112', /^11-12\.SL\.[46]$/)], ['Presentation and oral defense|Presentation plus answers to evaluators’ questions; worth 25% of the AP Research score.', 'Research process and reflection portfolio|Record of research steps and reflections kept throughout the year.', 'Poise|Confident, composed delivery.', 'Visual aid|Slides or posters that support a talk.']),
  ]),
};

// ------------------------------------------------------------------ Music (AZ music standards + AP Music Theory)
const MUS_ELEM = ['Pitch|How high or low a sound is.', 'Rhythm|The pattern of long and short sounds in time.', 'Meter|The grouping of beats into measures (e.g. 4/4, 3/4, 6/8).', 'Dynamics|How loud or soft music is (p, mf, f).', 'Tempo|The speed of the beat (Adagio, Andante, Allegro).', 'Timbre|The tone color that makes one instrument sound different from another.', 'Texture|How many layers of sound there are and how they relate (monophonic, homophonic, polyphonic).', 'Form|The structure of a piece (binary AB, ternary ABA, rondo, verse–chorus).'];
const lvl = { beg: ['Novice', 'Intermediate'], mid: ['Intermediate', 'Proficient'], adv: ['Proficient', 'Accomplished', 'Advanced'] };
export const DEEP_MUSIC = {
  aptheory: plan('AP Music Theory', [CB('ap-music-theory', 'AP Music Theory'), 'music_theory'], [
    unit('Unit 1: Music Fundamentals I — pitch, major scales and key signatures, rhythm, meter, expressive elements', ['Read pitches in treble, bass, alto and tenor clefs', 'Build major scales and identify major key signatures', 'Identify simple and compound meters and notate rhythms correctly'], ['Clef|Symbol showing which pitches the staff lines represent (treble, bass, alto, tenor).', 'Half step / whole step|Smallest interval in Western music / two half steps.', 'Major scale|W-W-H-W-W-W-H pattern of steps.', 'Key signature|Sharps or flats at the start of a staff that define the key.', 'Circle of fifths|Keys arranged by perfect fifths, adding one sharp or flat each step.', 'Simple meter|Beats divide into two (2/4, 3/4, 4/4).', 'Compound meter|Beats divide into three (6/8, 9/8, 12/8).', 'Syncopation|Accents on weak beats or off-beats.']),
    unit('Unit 2: Music Fundamentals II — minor scales and key signatures, melody, timbre, texture', ['Build natural, harmonic and melodic minor scales', 'Identify relative and parallel keys', 'Name and invert intervals by size and quality', 'Describe melodic contour, timbre and texture'], ['Relative minor|Minor key sharing a key signature with a major key (down a minor 3rd).', 'Parallel minor|Minor key with the same tonic as a major key.', 'Harmonic minor|Natural minor with a raised 7th degree.', 'Melodic minor|Raised 6th and 7th ascending; natural minor descending.', 'Interval quality|Perfect, major, minor, augmented or diminished.', 'Interval inversion|Flipping an interval; sizes add to 9 and qualities swap (M↔m, A↔d, P stays P).', 'Transposition|Moving music to a different pitch level.', 'Contour|The overall shape of a melody.']),
    unit('Unit 3: Music Fundamentals III — triads and seventh chords', ['Spell major, minor, diminished and augmented triads', 'Spell seventh chords and identify inversions with figured bass', 'Label chords with Roman numerals in major and minor keys'], ['Triad|Three-note chord built in thirds (root, third, fifth).', 'Seventh chord|Four-note chord adding a seventh above the root.', 'Inversion|Chord with a note other than the root in the bass.', 'Figured bass|Numbers showing intervals above the bass (6, 6/4, 7, 6/5, 4/3, 4/2).', 'Roman numeral analysis|Labeling chords by scale degree (I, ii, iii, IV, V, vi, vii°).', 'Dominant seventh (V7)|Major triad plus a minor seventh, built on scale degree 5.', 'Harmonic dictation|Writing down chords and bass line from listening.']),
    unit('Unit 4: Harmony and Voice Leading I — chord function, cadence, phrase', ['Write four-part chorales following voice-leading rules', 'Identify tonic, predominant and dominant function', 'Identify cadence types and phrase structure'], ['SATB|Soprano, alto, tenor, bass voices in four-part writing.', 'Parallel fifths/octaves|Two voices moving in perfect fifths or octaves in the same direction; avoided in common practice style.', 'Authentic cadence|V–I (perfect authentic when root position with tonic in soprano).', 'Half cadence|Phrase ending on V.', 'Plagal cadence|IV–I.', 'Deceptive cadence|V–vi.', 'Period|Two phrases (antecedent, consequent) ending with a weaker then stronger cadence.']),
    unit('Unit 5: Harmony and Voice Leading II — chord progressions and predominant function', ['Use predominant chords (ii, IV) in progressions', 'Use cadential 6/4 and other six-four chords correctly', 'Harmonize a melody or figured bass'], ['Predominant|Chords (ii, IV) that lead to the dominant.', 'Cadential 6/4|I6/4 chord embellishing V at a cadence.', 'Passing 6/4|Six-four chord over a stepwise bass between two chords.', 'Pedal 6/4|Six-four chord over a sustained bass note.', 'Harmonic rhythm|How often chords change.', 'Leading tone|Scale degree 7, which pulls up to tonic.']),
    unit('Unit 6: Harmony and Voice Leading III — embellishments, motives, melodic devices', ['Explain how motives are developed through repetition, sequence and variation', 'Identify non-chord tones in melody and harmony', 'Recognize motivic development techniques'], ['Passing tone|Non-chord tone moving stepwise between two chord tones.', 'Neighbor tone|Steps away from a chord tone and returns.', 'Suspension|A held note that resolves down by step (4-3, 7-6, 9-8).', 'Appoggiatura|Leap to a non-chord tone that resolves by step.', 'Anticipation|Arrives early on a note of the next chord.', 'Sequence|A pattern repeated at a different pitch level.', 'Motive|A short musical idea developed through a piece.']),
    unit('Unit 7: Harmony and Voice Leading IV — secondary function', ['Write secondary dominants in four-part harmony with correct resolutions', 'Spell and resolve secondary dominant and leading-tone chords', 'Identify tonicization and modulation to closely related keys'], ['Secondary dominant|Dominant of a chord other than tonic (e.g. V/V).', 'Secondary leading-tone chord|vii° of a chord other than tonic (e.g. vii°7/V).', 'Tonicization|Briefly treating a non-tonic chord as a temporary tonic.', 'Modulation|Moving to a new key and establishing it.', 'Closely related keys|Keys whose signatures differ by at most one accidental.', 'Pivot chord|A chord shared by two keys used to modulate.']),
    unit('Unit 8: Modes and form', ['Identify phrase relationships and sections (verse, chorus, bridge) in popular forms', 'Identify modes by their characteristic scale degrees', 'Identify common forms by ear and in a score'], ['Dorian|Minor mode with a raised 6th.', 'Phrygian|Minor mode with a lowered 2nd.', 'Lydian|Major mode with a raised 4th.', 'Mixolydian|Major mode with a lowered 7th.', 'Binary form|Two sections (AB).', 'Ternary form|Three sections, the first returning (ABA).', 'Rondo|Recurring A section alternating with contrasts (ABACA).', 'Theme and variations|A theme followed by altered versions.']),
    unit('AP exam skills', ['Use a practice schedule for aural skills (dictation daily, sight-singing weekly)', 'Practice melodic and harmonic dictation and sight-singing', 'Know the AP Music Theory exam sections'], ['Harmonic dictation|Writing the bass line and Roman numerals of a progression you hear.', 'Melodic dictation|Writing down a melody you hear.', 'Sight-singing|Singing a melody from notation without rehearsal.', 'Solfège|Do-re-mi syllables for scale degrees.', 'AP exam Section I|Multiple-choice questions with and without audio.', 'AP exam Section II|Free response: dictation, part writing, harmonization and sight-singing.']),
  ]),
  musictheory: plan('Music Theory', ['music_theory'], [
    unit('Elements of music & notation', [arts('music_theory', 'respond', ['Proficient'], 3)], MUS_ELEM),
    unit('Scales, keys & intervals', ['Build major and minor scales and identify key signatures', 'Name intervals by size and quality', 'Hear the difference between major and minor scales and intervals'], ['Major scale|W-W-H-W-W-W-H.', 'Natural minor scale|W-H-W-W-H-W-W.', 'Key signature|Sharps or flats that define the key.', 'Interval|The distance between two pitches.', 'Octave|Interval of eight letter names; frequency ratio 2:1.', 'Circle of fifths|Keys ordered by fifths.']),
    unit('Chords & harmony', ['Spell triads and seventh chords', 'Label chords with Roman numerals and identify cadences', 'Harmonize a simple melody with I, IV and V'], ['Triad|Three-note chord in thirds.', 'Root position|Chord with the root in the bass.', 'Roman numerals|Chord labels by scale degree.', 'Cadence|A harmonic ending of a phrase.', 'Dominant|Chord on scale degree 5, which pulls to tonic.', 'Tonic|The home chord of a key.']),
    unit('Composing & arranging', [arts('music_theory', 'create', lvl.adv, 5)], ['Motive|A short musical idea.', 'Phrase|A musical sentence ending with a cadence.', 'Melodic contour|The shape of a melody.', 'Arrangement|Adapting music for different instruments or voices.', 'Notation software|Programs (e.g. MuseScore) used to write music.']),
    unit('Analysis & performance', [arts('music_theory', 'perform', ['Proficient', 'Accomplished'], 4)], ['Score|Written music showing all parts.', 'Rehearsal plan|Steps for preparing a piece.', 'Interpretation|Performer’s expressive choices.', 'Style|Characteristic features of a period or genre.']),
    unit('Music in context', [arts('music_theory', 'connect', lvl.adv, 4)], ['Baroque (1600–1750)|Era of Bach and Handel; ornamentation and counterpoint.', 'Classical (1750–1820)|Era of Haydn and Mozart; balanced phrases.', 'Romantic (1820–1900)|Era of expressive, large-scale works.', 'Twentieth century|Era of new tonalities, rhythms and technology.']),
  ]),
  musichum: plan('Music Humanities', ['music_theory'], [
    unit('Listening & the elements of music', [arts('music_theory', 'respond', lvl.adv, 4)], MUS_ELEM),
    unit('Early music: Medieval, Renaissance & Baroque', ['Describe the musical style of each era and key composers', arts('music_theory', 'connect', ['Proficient'], 2)], ['Gregorian chant|Monophonic Latin sacred song of the Middle Ages.', 'Polyphony|Several independent melodic lines at once.', 'Renaissance (1450–1600)|Era of Josquin and Palestrina; vocal polyphony.', 'Baroque (1600–1750)|Era of Bach, Handel, Vivaldi; basso continuo.', 'Fugue|A piece where a subject is imitated in several voices.', 'Opera|A drama set to music, born around 1600.']),
    unit('Classical & Romantic eras', ['Listen for and describe orchestration differences between eras', 'Compare Classical and Romantic style', 'Identify sonata form and the symphony'], ['Classical era (1750–1820)|Haydn, Mozart, early Beethoven; clarity and balance.', 'Sonata form|Exposition, development, recapitulation.', 'Symphony|A large multi-movement work for orchestra.', 'Romantic era (1820–1900)|Schubert, Chopin, Wagner; emotion and nationalism.', 'Program music|Instrumental music that tells a story or depicts a scene.', 'Art song (Lied)|Song for voice and piano setting a poem.']),
    unit('20th-century & American music', ['Connect American popular styles to their African American roots', 'Trace jazz, blues and popular music', 'Describe new approaches to composition in the 20th century'], ['Blues|African American genre with a 12-bar form and blue notes.', 'Jazz|American style built on improvisation and swing.', 'Impressionism|Debussy and Ravel; color and atmosphere.', 'Minimalism|Repetitive patterns that change gradually (Reich, Glass).', 'Rock and roll|1950s popular style from blues and country.', 'Hip-hop|Genre built on rap, sampling and beats (1970s Bronx).']),
    unit('World music & music in society', [arts('music_theory', 'connect', ['Accomplished', 'Advanced'], 3)], ['Ethnomusicology|The study of music in its cultural context.', 'Mariachi|Mexican ensemble of violins, trumpets and guitars.', 'Gamelan|Indonesian ensemble of tuned percussion.', 'Raga|Melodic framework in Indian classical music.', 'Call and response|A phrase answered by another, common in African music.']),
  ]),
  orchestra: plan('Orchestra', ['ensemble'], [
    unit('Instrument technique', ['Demonstrate correct posture, bow hold and left-hand position', arts('ensemble', 'perform', ['Intermediate'], 3)], ['Bow hold|How the hand grips the bow.', 'Arco|Play with the bow.', 'Pizzicato|Pluck the strings.', 'Intonation|Playing in tune.', 'Shifting|Moving the left hand to a new position.', 'Vibrato|Slight, regular pitch variation for warmth.']),
    unit('Reading & rhythm', [arts('ensemble', 'respond', ['Intermediate', 'Proficient'], 3)], ['Time signature|Shows beats per measure and the note that gets one beat.', 'Ledger lines|Short lines for notes above or below the staff.', 'Dotted rhythm|A dot adds half the note’s value.', 'Key signature|Sharps or flats for the piece.', 'Sight-reading|Playing music at first sight.']),
    unit('Ensemble skills', [arts('ensemble', 'perform', ['Proficient'], 4)], ['Balance|Relative volume of parts.', 'Blend|How well sounds merge.', 'Conductor cues|Gestures showing tempo, dynamics and entrances.', 'Bowings|Up-bow (V) and down-bow (⊓) markings.', 'Section leader|Player who leads a section.']),
    unit('Rehearsal & performance', [arts('ensemble', 'perform', ['Accomplished', 'Advanced'], 3)], ['Concert etiquette|Expected audience and performer behavior.', 'Tuning|Adjusting to a reference pitch (A = 440 Hz).', 'Phrasing|Shaping musical sentences.', 'Articulation|How notes start and connect (legato, staccato, accent).']),
    unit('Creating & connecting', [arts('ensemble', 'create', ['Proficient'], 2), arts('ensemble', 'connect', ['Proficient'], 2)], ['Improvisation|Creating music spontaneously.', 'Arrangement|Adapting music for a new ensemble.', 'Orchestra families|Strings, woodwinds, brass, percussion.', 'Concerto|Work for soloist and orchestra.']),
  ]),
  guitar: plan('Guitar', ['harmonizing'], [
    unit('Guitar basics', ['Tune the guitar and use correct posture and hand position', arts('harmonizing', 'perform', ['Novice'], 2)], ['Standard tuning|E-A-D-G-B-E from lowest to highest string.', 'Fret|Metal strip that divides the neck into half steps.', 'Tablature (tab)|Notation showing strings and frets.', 'Pick / plectrum|Small tool for strumming or picking.', 'Capo|Clamp that raises the pitch of all strings.']),
    unit('Chords & strumming', [arts('harmonizing', 'perform', ['Intermediate'], 3)], ['Open chord|Chord using open strings (G, C, D, E minor).', 'Barre chord|Index finger presses several strings across a fret.', 'Power chord|Root and fifth, common in rock.', 'Chord chart|Diagram showing finger placement.', 'Strumming pattern|Rhythm of down- and up-strokes.']),
    unit('Reading music & melody', [arts('harmonizing', 'respond', ['Intermediate', 'Proficient'], 3)], ['Standard notation|Notes on the staff.', 'Fingerpicking|Plucking strings with the fingers.', 'Scale|Series of notes in order (e.g. pentatonic).', 'Position playing|Keeping the hand in one area of the neck.']),
    unit('Harmony & accompaniment', [arts('harmonizing', 'create', ['Intermediate', 'Proficient'], 4)], ['I–IV–V progression|The most common chord progression.', '12-bar blues|A standard 12-measure chord progression.', 'Transposition|Moving a song to a new key.', 'Accompaniment|Chords supporting a melody.']),
    unit('Performance & style', [arts('harmonizing', 'perform', ['Proficient', 'Accomplished'], 3), arts('harmonizing', 'connect', ['Proficient'], 2)], ['Classical guitar|Nylon-string guitar and fingerstyle repertoire.', 'Flamenco|Spanish style with rasgueado strumming.', 'Improvisation|Creating a solo on the spot.', 'Stage presence|Confident performance behavior.']),
  ]),
  piano: plan('Piano', ['harmonizing'], [
    unit('Keyboard basics', ['Find notes on the keyboard and use correct posture and finger numbers', arts('harmonizing', 'perform', ['Novice'], 2)], ['Middle C|The C near the center of the keyboard.', 'Finger numbers|Thumb = 1 through pinky = 5.', 'Grand staff|Treble and bass staves joined.', 'Sharp / flat|Raises / lowers a note a half step.', 'Black keys|Groups of two and three that help locate notes.']),
    unit('Reading & rhythm', [arts('harmonizing', 'respond', ['Intermediate'], 3)], ['Treble clef|Usually played by the right hand.', 'Bass clef|Usually played by the left hand.', 'Time signature|Beats per measure.', 'Sustain pedal|Right pedal that lets notes ring.', 'Legato / staccato|Smooth / detached.']),
    unit('Scales & technique', [arts('harmonizing', 'perform', ['Intermediate', 'Proficient'], 3)], ['Major scale|W-W-H-W-W-W-H.', 'Thumb crossing|Passing the thumb under to play scales smoothly.', 'Arpeggio|Notes of a chord played one at a time.', 'Hand independence|Playing different rhythms in each hand.']),
    unit('Chords & accompaniment', [arts('harmonizing', 'create', ['Intermediate', 'Proficient'], 4)], ['Triad|Three-note chord.', 'Inversion|Rearranged chord with a different bass note.', 'Lead sheet|Melody with chord symbols.', 'Alberti bass|Broken-chord accompaniment pattern.']),
    unit('Repertoire & performance', [arts('harmonizing', 'perform', ['Accomplished', 'Advanced'], 3), arts('harmonizing', 'connect', ['Proficient'], 2)], ['Sonatina|A short, simple sonata.', 'Etude|A study piece for technique.', 'Dynamics|Volume markings (p, f, crescendo).', 'Recital|Solo performance for an audience.']),
  ]),
};

// ------------------------------------------------------------------ Electives & support courses
const STUDY = ['Retrieval practice|Recalling information from memory (self-quizzing) to strengthen learning.', 'Spaced practice|Studying in several short sessions spread over days instead of cramming.', 'Interleaving|Mixing different topics or problem types in one study session.', 'Elaboration|Explaining how and why ideas work and connect.', 'Concrete examples|Using specific examples to understand abstract ideas.', 'Dual coding|Combining words with visuals such as diagrams or timelines.'];
const MIND = ['Growth mindset|Belief that abilities can grow with effort and good strategies.', 'Self-efficacy|Belief in your ability to succeed at a task.', 'Self-advocacy|Speaking up for what you need to learn.', 'Self-regulation|Managing emotions, attention and behavior to reach goals.', 'Resilience|Recovering from setbacks.'];
const CAREER = [
  unit('Self-awareness & career exploration', [std('proskills', /^5\.C$/), 'Identify interests, strengths and values with career inventories', 'Research careers: duties, education, pay and outlook'], ['Career cluster|A group of related careers (e.g. Health Science, IT).', 'Interest inventory|A survey matching interests to careers.', 'Occupational Outlook Handbook|U.S. Bureau of Labor Statistics guide to careers, pay and job outlook.', 'Postsecondary options|College, community college, trade school, apprenticeship, military, work.', 'Transferable skills|Skills useful in many jobs.']),
  unit('Communication & teamwork at work', [std('proskills', /^(1\.[ABC]|2\.[AB])$/)], ['Active listening|Fully focusing on and responding to a speaker.', 'Professional email|Clear subject, greeting, concise message, closing.', 'Teamwork|Working cooperatively toward shared goals.', 'Conflict resolution|Solving disagreements respectfully.', 'Customer service|Helping customers courteously and effectively.']),
  unit('Job search skills', ['Write a résumé and cover letter', 'Complete job applications accurately', 'Prepare for and practice job interviews'], ['Résumé|One-page summary of skills, education and experience.', 'Cover letter|Letter introducing yourself for a specific job.', 'Reference|Someone who can vouch for your character or work.', 'Interview|Meeting where an employer evaluates a candidate.', 'STAR method|Answering interview questions with Situation, Task, Action, Result.', 'Networking|Building relationships that can lead to opportunities.']),
  unit('Professionalism & workplace expectations', [std('proskills', /^(4\.[A-F]|5\.[AB])$/)], ['Punctuality|Being on time.', 'Dress code|Employer rules for appearance.', 'Initiative|Doing what needs to be done without being told.', 'Feedback|Information about your performance used to improve.', 'Probation period|Trial period at the start of a job.']),
  unit('Workplace laws, safety & ethics', [std('proskills', /^8\.[A-I]$/)], ['Minimum wage|Lowest hourly pay allowed by law (Arizona sets its own rate).', 'Child labor laws|Rules limiting hours and jobs for workers under 18.', 'OSHA|Federal agency for workplace safety.', 'Harassment|Unwelcome conduct that creates a hostile workplace; illegal.', 'Confidentiality|Keeping private information private.', 'Integrity|Being honest and trustworthy.']),
  unit('Paychecks & personal finance', [std('proskills', /^9\.[A-C]$/), std('hss', /^HS\.E1\.[1-3]$/)], ['Gross pay|Earnings before deductions.', 'Net pay|Take-home pay after deductions.', 'Form W-4|Sets tax withholding.', 'Form I-9|Verifies identity and eligibility to work.', 'Budget|A plan for income and spending.', 'Direct deposit|Pay sent electronically to a bank account.']),
];

export const DEEP_ELECT = {
  studyskills: plan('Study Skills & Academic Support', [ASCA, LSCI, 'edtech'], [
    unit('Mindsets for learning', ['Believe in your ability to grow and learn (ASCA mindset)', 'Balance school, activities and well-being', 'Set short- and long-term academic goals'], [...MIND, 'SMART goal|Specific, Measurable, Achievable, Relevant, Time-bound goal.']),
    unit('How memory works', ['Recognize the illusion of competence and test yourself instead', 'Explain why cramming fades and spacing lasts', 'Use retrieval practice instead of rereading'], ['Encoding|Getting information into memory.', 'Forgetting curve|Memory fades quickly without review.', 'Working memory|Limited “mental workspace” for current thinking.', 'Long-term memory|Durable storage built through practice and meaning.', 'Illusion of competence|Feeling you know material because it looks familiar.']),
    unit('Six evidence-based study strategies', ['Explain why each strategy works, with an example from one of your classes', 'Plan a week of studying using spacing, retrieval and interleaving', 'Turn notes into practice questions and flashcards'], STUDY),
    unit('Notes, reading & organization', ['Take organized notes (Cornell, outline, mapping)', 'Use active reading strategies', std('edtech', /^9-12\.3\.[ac]$/)], ['Cornell notes|Notes with cues, main notes and a summary.', 'SQ3R|Survey, Question, Read, Recite, Review.', 'Annotation|Marking a text with notes and questions.', 'Planner|Tool for tracking assignments and due dates.', 'Graphic organizer|Visual chart for organizing ideas.']),
    unit('Time management & planning', ['Break large assignments into steps with deadlines', 'Prioritize tasks and limit distractions', 'Use self-discipline and self-control (ASCA behavior)'], ['Prioritizing|Doing the most important tasks first.', 'Procrastination|Putting off tasks.', 'Pomodoro technique|Focused 25-minute work blocks with short breaks.', 'Chunking|Breaking a big task into smaller parts.', 'Eisenhower matrix|Sorting tasks by urgent vs. important.']),
    unit('Test preparation & self-advocacy', ['Prepare for tests with practice tests and review plans', 'Manage test anxiety', 'Ask teachers for help and use school supports'], ['Practice test|Self-test under test-like conditions.', 'Test anxiety|Stress that interferes with performance.', 'Process of elimination|Ruling out wrong answer choices.', 'Office hours / tutoring|Extra help from teachers or tutors.', 'Accommodation|A support that changes how a student learns or is tested (e.g. extended time).']),
  ]),
  advisory: plan('Advisory', [ASCA, CASEL], [
    unit('Self-awareness', ['Reflect on how emotions affect decisions and learning', 'Identify your emotions, strengths and values', 'Show a sense of belonging in the school environment (ASCA mindset)'], ['Mindfulness|Paying attention to the present moment without judgment.', 'Self-awareness|Understanding your emotions, thoughts and values.', 'Emotional vocabulary|Words to name feelings precisely.', 'Strengths|Things you do well.', 'Values|Beliefs about what is important.']),
    unit('Self-management', ['Use stress-management and coping strategies', 'Set goals and monitor progress', 'Demonstrate perseverance and self-discipline (ASCA behaviors)'], [...MIND, 'Coping strategy|A healthy way to handle stress.']),
    unit('Social awareness & relationships', ['Show empathy and respect for different perspectives', 'Build positive relationships with peers and adults', 'Resolve conflict constructively'], ['Empathy|Understanding and sharing another’s feelings.', 'Perspective-taking|Seeing a situation from another’s view.', 'Healthy relationship|Relationship built on respect and trust.', 'I-statement|“I feel… when… because…” to express concerns.', 'Bystander|Someone who witnesses harm; an upstander intervenes.']),
    unit('Responsible decision-making', ['Evaluate the consequences of choices for yourself and others', 'Make ethical, safe decisions and consider consequences', 'Use a decision-making model'], ['Ethical decision|A choice that considers what is right and fair for everyone affected.', 'Decision-making model|Define, list options, weigh consequences, decide, reflect.', 'Peer pressure|Influence from peers to act a certain way.', 'Digital footprint|The trail of information you leave online.', 'Consequence|The result of a choice.']),
    unit('Academic & college/career planning', ['Track grades and credits toward graduation', 'Explore postsecondary and career options', 'Build a 4-year plan'], ['Credit|Unit earned for passing a course.', 'GPA|Grade point average.', 'Transcript|Official record of courses and grades.', 'ECAP|Arizona Education and Career Action Plan.', 'FAFSA|Free Application for Federal Student Aid.']),
  ]),
  peer: plan('Peer-Facilitator', ['council', ASCA, CASEL], [
    unit('Role of a peer facilitator', ['Practice helping skills through role-play', 'Explain the helper’s role, boundaries and confidentiality', 'Know when to refer a peer to an adult'], ['Role-play|Practicing a situation by acting it out.', 'Referral|Connecting someone with an adult or service that can help.', 'Peer facilitator|A trained student who supports classmates.', 'Confidentiality|Keeping shared information private (except safety concerns).', 'Mandatory referral|Situations, such as harm to self or others, that must be reported to an adult.', 'Boundaries|Limits that keep a helping relationship healthy.']),
    unit('Communication & listening', [std('council', /^1\.[13]\.[a-e]$/, 6)], ['Active listening|Attending, paraphrasing and asking questions.', 'Paraphrasing|Restating what someone said in your own words.', 'Open-ended question|Question that invites more than yes/no.', 'Nonverbal cues|Body language, eye contact and tone.']),
    unit('Tutoring & study support', ['Give specific, encouraging feedback', 'Use questioning to guide rather than give answers', 'Model effective study strategies'], [...STUDY.slice(0, 3), 'Scaffolding|Support that fades as skill grows.', 'Wait time|Pausing after a question to let someone think.']),
    unit('Group process & conflict resolution', [std('council', /^[67]\.\d\.[a-e]$/, 7)], ['Stages of group development|Forming, storming, norming, performing.', 'Mediation|A neutral helper guides two sides to agreement.', 'Consensus|A decision everyone can support.', 'Win-win|Outcome meeting both sides’ needs.']),
    unit('Character & inclusion', [std('council', /^(3|9)\.\d\.[a-e]$/, 6)], ['Inclusion|Making sure everyone feels welcome.', 'Respect|Treating others with dignity.', 'Bias|Unfair preference for or against a group.', 'Mentor|A trusted guide and role model.']),
  ]),
  aide: plan('Student Aides', ['proskills'], [
    unit('Professional conduct in the office or classroom', [std('proskills', /^4\.[A-F]$/)], ['Professionalism|Meeting expectations for behavior and work quality.', 'Punctuality|Being on time and ready.', 'Discretion|Using good judgment about what to say and share.', 'Chain of command|Who to go to with questions or problems.']),
    unit('Confidentiality & ethics', [std('proskills', /^8\.[ABDHI]$/), 'Explain why student records are private under FERPA'], ['FERPA|Federal law protecting the privacy of student education records.', 'Confidential information|Grades, records and personal details that must not be shared.', 'Integrity|Being honest and trustworthy.', 'Need to know|Sharing information only with those who require it.']),
    unit('Office & communication skills', [std('proskills', /^1\.[A-D]$/)], ['Phone etiquette|Greeting, identifying yourself, taking clear messages.', 'Filing|Organizing documents so they can be found.', 'Message slip|Note recording caller, time, message and callback number.', 'Customer service|Helping visitors courteously.']),
    unit('Initiative & organization', [std('proskills', /^(5\.[A-B]|7\.[A-C])$/)], ['Initiative|Seeing what needs doing and doing it.', 'Task list|A prioritized list of things to do.', 'Organizational culture|The shared values and practices of a workplace.', 'Reliability|Being dependable.']),
    unit('Technology & reflection', [std('proskills', /^(1\.C|2\.C|3\.B)$/), 'Keep a log of tasks completed and skills learned'], ['Spreadsheet|Grid program for lists and data.', 'Shared calendar|Online calendar for scheduling.', 'Reflection log|Notes on what you did and learned.', 'Transferable skill|A skill useful in many jobs.', 'Letter of recommendation|Letter from a supervisor describing your strengths.']),
  ]),
  career: plan('Career Development & Work Experience', ['proskills', ASCA], CAREER),
  council: plan('Student Government', ['council'], [
    unit('Communication', [std('council', /^1\.[1-4]\.[a-e]$/, 10)], ['Public speaking|Presenting ideas to an audience.', 'Audience analysis|Adjusting a message to the listeners.', 'Agenda|Ordered list of items for a meeting.', 'Minutes|Official written record of a meeting.', 'Press release|Announcement written for media.']),
    unit('Organization & meetings', [std('council', /^2\.[1-4]\.[a-c]$/, 10)], ['Parliamentary procedure|Rules for orderly meetings.', 'Robert’s Rules of Order|Widely used guide to parliamentary procedure.', 'Motion|A formal proposal for action.', 'Quorum|Minimum members needed to conduct business.', 'Constitution and bylaws|Documents defining an organization’s rules.', 'Budget|Plan for income and spending of student funds.']),
    unit('Character & ethics', [std('council', /^3\.\d\.[a-e]$/)], ['Ethics|Principles of right and wrong conduct.', 'Servant leadership|Leading by serving others.', 'Six pillars of character|Trustworthiness, respect, responsibility, fairness, caring, citizenship.', 'Accountability|Taking responsibility for actions.']),
    unit('Goal setting & project planning', [std('council', /^4\.1\.[a-c]$/), std('council', /^2\.2\.[a-c]$/)], ['SMART goal|Specific, Measurable, Achievable, Relevant, Time-bound.', 'Action plan|Steps, owners and deadlines to reach a goal.', 'Timeline|Schedule of tasks.', 'Evaluation|Measuring whether goals were met.', 'Delegation|Assigning tasks to others.']),
    unit('Decision-making & group process', [std('council', /^[56]\.\d\.[a-e]$/, 8)], ['Autocratic decision|Leader decides alone.', 'Democratic decision|Group votes.', 'Consensus|Agreement everyone can support.', 'Forming–storming–norming–performing|Tuckman’s stages of team development.', 'Groupthink|Seeking agreement at the expense of good decisions.']),
    unit('Conflict resolution, citizenship & diversity', [std('council', /^[789]\.\d\.[a-e]$/, 9)], ['Mediation|Neutral helper guiding agreement.', 'Compromise|Each side gives up something.', 'Service project|Activity that meets a community need.', 'Inclusion|Planning so everyone can take part.', 'Civic engagement|Taking part in community and public life.']),
  ]),
  techfac: plan('Technology Facilitator', ['edtech', 'cs'], [
    unit('Empowered learner & troubleshooting', [std('edtech', /^9-12\.1\./), std('cs', /^HS\.CS\.(T|HS)\.1$/)], ['Troubleshooting|Systematically finding and fixing a problem.', 'Help desk ticket|A logged support request.', 'Operating system|Software that manages hardware and runs apps.', 'Restart / clear cache|First steps that fix many issues.', 'Peripheral|External device such as a printer or projector.']),
    unit('Digital citizenship & security', [std('edtech', /^9-12\.2\./), std('cs', /^HS\.NI\.C\.[1-3]$/)], ['Digital citizenship|Safe, legal and ethical technology use.', 'Phishing|Fake messages that steal information.', 'Strong password|Long, unique passphrase; use a password manager.', 'Two-factor authentication|Second verification step at login.', 'Acceptable use policy|School rules for technology use.', 'Copyright & fair use|Rules for using others’ work.']),
    unit('Knowledge constructor & research tools', [std('edtech', /^9-12\.(3\.|b$)/)], ['Search operators|Quotes, minus and site: to refine searches.', 'Lateral reading|Checking a source by seeing what others say about it.', 'Citation manager|Tool that formats citations.', 'Cloud storage|Saving files online for access anywhere.']),
    unit('Supporting teachers & classrooms', [std('edtech', /^9-12\.(6|7)\./, 6)], ['LMS|Learning management system (e.g. Canvas).', 'Screen sharing|Displaying a device’s screen to others.', 'Tutorial|Step-by-step instructions for a task.', 'Accessibility features|Captions, screen readers, zoom.', 'Collaboration tools|Shared docs and video meetings.']),
    unit('Networks & hardware', [std('cs', /^HS\.(NI\.NCO|DA\.S)\.\d$/)], ['IP address|Number that identifies a device on a network.', 'Router|Device that forwards data between networks.', 'Wi-Fi|Wireless local network.', 'Bandwidth|Amount of data a connection can carry.', 'Binary|Base-2 system computers use.']),
  ]),
  gaming1: plan('Gaming Concepts 1', ['cs', ext('MDA: A Formal Approach to Game Design (Hunicke, LeBlanc & Zubek)', 'https://users.cs.northwestern.edu/~hunicke/MDA.pdf')], [
    unit('Games & their history', ['Explain how hardware advances shaped game design', 'Trace the history of video games from arcades to mobile', std('cs', /^HS\.IC\.C\.1$/)], ['Pong (1972)|Early commercial arcade video game by Atari.', 'Console generation|Era of home consoles with similar technology.', 'Indie game|Game made by a small independent team.', 'Esports|Organized competitive video gaming.', 'ESRB rating|Age and content rating for games.']),
    unit('Genres & game design basics', ['Write a one-page game design document', 'Classify games by genre and core loop', 'Analyze games with the MDA framework'], ['Genre|Category of game (platformer, RPG, puzzle, strategy, shooter, simulation).', 'Core loop|The main repeated cycle of play.', 'MDA framework|Mechanics, Dynamics, Aesthetics: a way to analyze games.', 'Mechanic|A rule or action available to the player.', 'Win condition|What a player must do to succeed.', 'Balance|Making choices fair and interesting.']),
    unit('Logic & programming games', [std('cs', /^HS\.AP\.(A|V|C)\.\d$/)], ['Variable|Named value such as score or health.', 'Event|An action that triggers code (key press, collision).', 'Conditional|If/then logic.', 'Loop|Code that repeats.', 'Sprite|A 2-D image or character in a game.', 'Game engine|Software for building games (e.g. Unity, Godot, GameMaker).']),
    unit('Level design & playtesting', ['Revise a level based on playtest data', std('cs', /^HS\.AP\.PD\.[12]$/)], ['Level design|Creating spaces, challenges and pacing.', 'Difficulty curve|How challenge increases over time.', 'Playtesting|Watching players to find problems.', 'Iteration|Improving a design through repeated cycles.', 'Prototype|An early, rough version to test ideas.']),
    unit('Careers & impacts of gaming', [std('cs', /^HS\.IC\.(SI|SLE)\.1$/), 'Identify careers in the game industry'], ['Game designer|Creates rules and systems.', 'Game artist|Creates visual assets.', 'QA tester|Finds bugs.', 'Producer|Manages schedules and teams.', 'Intellectual property|Legal rights to creative work.']),
  ]),
  gaming2: plan('Gaming Concepts 2', ['cs', 'software'], [
    unit('Game programming', [std('cs', /^HS\.AP\.(M|C)\.\d$/)], ['Function|Reusable block of code.', 'Object|Bundle of data and behavior (e.g. an enemy).', 'Collision detection|Checking when objects touch.', 'Game loop|Update and draw repeated every frame.', 'Frame rate|Frames drawn per second.']),
    unit('Math & physics for games', ['Use trigonometry to aim or rotate objects', 'Use coordinates, vectors and velocity to move objects', 'Apply gravity and simple physics'], ['Coordinate system|x, y (and z) positions.', 'Vector|Quantity with magnitude and direction.', 'Velocity|Speed with direction.', 'Delta time|Time between frames used for smooth movement.', 'Random number|Used for variety and chance.']),
    unit('Art, audio & user interface', [std('software', (i) => /User Design/.test(i[2]), 4)], ['UI|User interface: menus, HUD, buttons.', 'HUD|Heads-up display showing health, score, map.', 'Sprite sheet|Image holding animation frames.', 'Sound effect|Short audio cue for an action.', 'Accessibility options|Remappable controls, subtitles, colorblind modes.']),
    unit('Team production & version control', [std('software', (i) => /Version Control/.test(i[2]), 4), std('cs', /^HS\.AP\.PD\.2$/)], ['Git|Version control system.', 'Sprint|Short, focused work period in agile development.', 'Bug report|Steps to reproduce, expected and actual results.', 'Milestone|A major checkpoint (alpha, beta, release).']),
    unit('Publishing a game', ['Write release notes and a store description for a game', std('cs', /^HS\.AP\.PD\.1$/), std('cs', /^HS\.IC\.C\.2$/)], ['Release notes|Summary of changes in a new version.', 'Rating board|Organization that assigns age ratings (ESRB).', 'Build|Compiled, playable version of a game.', 'Postmortem|Reflection on what went right and wrong.', 'Monetization|How a game earns money.', 'Portfolio|Collection showcasing your projects.']),
  ]),
  gifted: plan('Gifted Seminar H', ['edtech', 'hss', ext('Stanford d.school design thinking process', 'https://dschool.stanford.edu/resources')], [
    unit('Understanding giftedness & yourself', ['Develop strategies for managing stress and perfectionism', 'Describe your learning profile, strengths and interests', 'Recognize perfectionism and asynchronous development'], ['Self-advocacy|Speaking up for your learning needs.', 'Twice-exceptional (2e)|Gifted and also having a learning difference or disability.', 'Asynchronous development|Uneven development across intellectual, emotional and physical areas.', 'Perfectionism|Setting unrealistically high standards; can block progress.', 'Overexcitabilities|Heightened intensity (Dabrowski) common in gifted learners.', 'Intrinsic motivation|Drive from interest rather than rewards.']),
    unit('Critical & creative thinking', [std('edtech', /^9-12\.5\.[acd]$/)], ['Divergent thinking|Generating many possible ideas.', 'Convergent thinking|Narrowing to the best solution.', 'Socratic seminar|Discussion driven by open questions about a text.', 'Logical fallacy|An error in reasoning (straw man, ad hominem, false dilemma).', 'Metacognition|Thinking about your thinking.']),
    unit('Design thinking', [std('edtech', /^9-12\.4\.[a-d]$/)], ['Empathize|Understand users’ needs.', 'Define|State the core problem.', 'Ideate|Brainstorm solutions.', 'Prototype|Build a quick model.', 'Test|Get feedback and refine.']),
    unit('Inquiry & research', [std('hss', /^HS\.SP3\.[1-4]$/), std('edtech', /^9-12\.b$/)], ['Compelling question|Open question worth investigating.', 'Primary source|Original evidence from the time studied.', 'Secondary source|Interpretation of primary sources.', 'Credibility|Trustworthiness of a source.']),
    unit('Communicating ideas', [std('edtech', /^9-12\.6\.[a-d]$/)], ['Audience|Who a message is for.', 'Pitch|Short persuasive presentation.', 'TED-style talk|Short talk built around one idea.', 'Visual storytelling|Using images and data to convey a message.']),
  ]),
  capstone: plan('Change the World Gifted Capstone', ['hss', 'edtech', ext('UN Sustainable Development Goals', 'https://sdgs.un.org/goals')], [
    unit('Choosing a real-world issue', [std('hss', /^HS\.C4\.[56]$/), 'Connect a local issue to a global challenge such as the UN Sustainable Development Goals'], ['Sustainable Development Goals|17 UN goals for 2030 (e.g. no poverty, climate action).', 'Root cause|The underlying reason a problem exists.', 'Stakeholder|Person or group affected by an issue.', 'Problem statement|Clear description of the problem to solve.']),
    unit('Investigating from multiple perspectives', [std('hss', /^HS\.SP(2\.[12]|3\.[2-4])$/)], ['Perspective|A viewpoint shaped by background and values.', 'Interdisciplinary|Using several fields of study.', 'Data literacy|Reading and questioning data critically.', 'Interview|Gathering first-hand perspectives.']),
    unit('Designing a solution', [std('edtech', /^9-12\.4\.[a-d]$/)], ['Design thinking|Empathize, define, ideate, prototype, test.', 'Feasibility|Whether a solution can realistically be done.', 'Prototype|Early model of a solution.', 'Constraint|A limit such as time, money or rules.']),
    unit('Taking action & collaborating', [std('hss', /^HS\.C4\.7$/), std('edtech', /^9-12\.7\.[b-d]$/)], ['Action plan|Steps, roles and timeline.', 'Advocacy|Speaking up to influence decisions.', 'Partnership|Working with organizations or experts.', 'Impact metric|A measure of a project’s effect.']),
    unit('Presenting & reflecting', [std('hss', /^HS\.SP3\.[68]$/), std('edtech', /^9-12\.6\.d$/)], ['Exhibition|Public presentation of a capstone.', 'Reflection|Thinking about growth and lessons learned.', 'Executive summary|One-page overview of a project.', 'Call to action|What you want the audience to do.']),
  ]),
  elalab: plan('English Language Arts Lab', ['ela910', LSCI], [
    unit('Close reading of literature', [std('ela910', /^9-10\.RL\.[1-3]$/)], ['Annotation|Marking a text with notes, questions and connections.', 'Textual evidence|Quotes or details that support an answer.', 'Inference|A conclusion from clues plus prior knowledge.', 'Theme|The message or insight of a work.', 'Summary|Short retelling of the most important ideas.', 'Character motivation|Why a character acts as they do.']),
    unit('Reading informational texts', [std('ela910', /^9-10\.RI\.[1-3]$/), std('ela910', /^9-10\.RI\.8$/)], ['Central idea|The main point of an informational text.', 'Text structure|How a text is organized (cause-effect, compare-contrast, problem-solution).', 'Claim|An arguable statement.', 'Author’s purpose|Why the author wrote (inform, persuade, entertain).', 'Text features|Headings, captions, charts and bold words.', 'Fact vs opinion|Provable statement vs. belief.']),
    unit('Vocabulary strategies', [std('ela910', /^9-10\.L\.[456]$/)], ['Context clues|Nearby words that hint at meaning.', 'Root / prefix / suffix|Word parts that build meaning.', 'Connotation|Feeling or idea a word suggests.', 'Denotation|Dictionary meaning.', 'Academic vocabulary|Words used across subjects (analyze, evaluate, infer).', 'Figurative language|Non-literal language (simile, metaphor).']),
    unit('Writing paragraphs & essays', [std('ela910', /^9-10\.W\.[1245]$/)], ['Claim-evidence-reasoning|Structure: state a claim, give evidence, explain how it supports the claim.', 'Topic sentence|Sentence stating a paragraph’s main idea.', 'Embedded quotation|Quote blended into your own sentence.', 'Transition|Word linking ideas (however, therefore).', 'Revision|Improving ideas and organization.', 'Editing|Fixing grammar, spelling and punctuation.']),
    unit('Grammar & conventions', [std('ela910', /^9-10\.L\.[12]$/), std('ela910', /^9-10\.L\.[12][abc]$/, 4)], ['Complete sentence|Subject + verb + complete thought.', 'Fragment|Incomplete sentence.', 'Run-on|Two sentences joined incorrectly.', 'Comma splice|Two sentences joined only by a comma.', 'Semicolon|Joins related independent clauses.', 'Parallel structure|Matching grammatical forms in a series.']),
    unit('Study & test strategies for English', ['Track progress with self-quizzes and adjust your study plan', 'Use retrieval practice and spaced review for vocabulary and texts', 'Plan timed writing: read, outline, draft, check'], STUDY),
  ]),
  acadeca: plan('Academic Decathlon H — 2026–27: Journeys of Transformation (travel & transportation)', [USAD], [
    unit('Literature — journeys & quests; The Remains of the Day (Kazuo Ishiguro)', ['Compare journey narratives across the selected shorter works', 'Analyze how journeys shape character and theme', 'Read critically: tone, narrator reliability and structure'], ['The Remains of the Day|1989 novel by Kazuo Ishiguro; a butler’s road trip prompts reflection on duty and regret.', 'Unreliable narrator|A narrator whose account cannot be fully trusted.', 'Quest narrative|Story built around a journey toward a goal.', 'Frame narrative|A story within a story.', 'Stream of consciousness|Narration following a character’s flow of thoughts.', 'Kazuo Ishiguro|British novelist; 2017 Nobel Prize in Literature.']),
    unit('Economics — fundamentals, micro, macro & economics of transportation', [std('hss', /^HS\.E[234]\.[1-3]$/, 6)], ['Scarcity|Limited resources vs. unlimited wants.', 'Elasticity|How much quantity responds to price changes.', 'Externality|A cost or benefit affecting third parties (e.g. traffic pollution).', 'GDP|Total value of final goods and services produced.', 'Fiscal vs monetary policy|Government spending/taxes vs. central bank control of money and interest rates.', 'Infrastructure|Roads, rails, ports and airports that support the economy.']),
    unit('Mathematics — general math, geometry & intro to differential calculus', [std('geo', /G-(SRT|GMD)\.[A-C]\.\d+$/, 3), 'Find derivatives using limits and basic rules', 'Interpret a derivative as a rate of change (e.g. velocity)'], ['Derivative|Instantaneous rate of change of a function.', 'Limit|Value a function approaches as input approaches a point.', 'Power rule|d/dx xⁿ = n·xⁿ⁻¹.', 'Velocity|Derivative of position with respect to time.', 'Similar triangles|Same shape; corresponding sides proportional.', 'Distance formula|d = √((x₂−x₁)² + (y₂−y₁)²).']),
    unit('Science — animal behavior & migration', ['Analyze data on migration timing and routes', 'Explain how climate change affects migration', 'Explain innate vs learned behavior and why animals migrate', 'Describe how animals navigate'], ['Migration|Seasonal, long-distance movement of animals.', 'Innate behavior|Behavior that is inherited, not learned.', 'Imprinting|Rapid learning early in life (e.g. ducklings follow their mother).', 'Magnetoreception|Sensing Earth’s magnetic field to navigate.', 'Circadian rhythm|Roughly 24-hour biological cycle.', 'Natural selection|Inherited traits that aid survival become more common.']),
    unit('Social science — human geography & migration', [std('hss', /^HS\.G3\.[1-5]$/)], ['Push and pull factors|Reasons people leave a place and are drawn to another.', 'Refugee|Person forced to flee persecution or conflict.', 'Diffusion|Spread of ideas or culture across space.', 'Urbanization|Growth of cities.', 'Demographic transition|Shift from high to low birth and death rates.', 'Remittance|Money migrants send home.']),
    unit('Art & music — travel and transportation in the arts', ['Compare how two works from different periods portray journeys', 'Analyze how artists and composers depict travel and motion', 'Identify works, styles and periods'], ['Hudson River School|19th-century American landscape painters.', 'Futurism|Early 20th-century movement celebrating speed and machines.', 'Ukiyo-e|Japanese woodblock prints, including Hiroshige’s Fifty-three Stations of the Tōkaidō.', 'Program music|Instrumental music depicting a scene or journey.', 'Train songs|Blues and folk songs using train imagery and rhythm.', 'Romanticism|19th-century emphasis on emotion, nature and travel.']),
    unit('Speech, interview & essay', ['Deliver a prepared and impromptu speech', 'Answer interview questions with poise', std('ela1112', /^11-12\.(SL\.4|W\.1)$/)], ['Prepared speech|Speech written and rehearsed in advance.', 'Impromptu speech|Speech given with little preparation.', 'Interview|One-on-one conversation judged on communication.', 'Essay|Timed written response to a prompt.', 'Super Quiz|Team-based relay event in Academic Decathlon.']),
  ]),
};
